id: P001762
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:19:55.332625
source_metadata:
  id: bdr:W3CN5459
  title: མཁས་འཇུག་གི་རྩ་བ་དང་སྡོམ་བྱང་།
  author: ''
  volumes:
    d447ef0e66674803b8f5e1010c627c44:
      image_group_id: I3CN5461
      title: ''
      volume_number: 1
      total_pages: 318
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
