id: IC40F3CFC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T10:39:48+00:00'
last_modified: '2022-06-07T15:03:40.813409+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5459
  title: མཁས་འཇུག་གི་རྩ་བ་དང་སྡོམ་བྱང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F344:
      image_group_id: I3CN5461
      title: ''
      total_pages: 318
      order: 1
      base_file: F344.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
